### ISSUE TITLE
Missing icon class selector

### ISSUE THREAD

**Issue by danyj** [swashata/IcoMoonIconIndexer#1]
First thank you for this great tool. There is small issue ,  on icoMoon app we have an option to use class for icons instead of data attribute ,  like

```
.myicons{
    font-family: 'Myicons';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    /* Better Font Rendering =========== */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

if we use that the icons are indexed without this prefix icon. config  HTML_ATTR  does not help either. I am trying to create JSON but it is missing the extra class.

Any help is appreciated

**Comment by swashata** [comment]
You need to look into `auto-generate.php` file for changing the `$class_prefix` variable.
